---
title: "get_tabs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
crosstab <- function(dframe, column, y_col) {
  dframe %>%
    group_by(!!sym(column), !!sym(y_col)) %>%
    summarise(n = n()) %>%
    pivot_wider(id_cols = !!sym(column),
                names_from = !!sym(y_col),
                values_from = n) %>% 
    mutate(
      `0` = ifelse(is.na(`0`)==1,0,`0`),
      `1` = ifelse(is.na(`1`)==1,0,`1`),
    )
}

xtab <- function(dframe, column, y_col){
  xtab <- crosstab(dframe, column, y_col) %>% 
    mutate(survival_ratio = `1` / (`1` + `0`))
  return(xtab)
}

distro_table <- function(dframe, column, y_col) {
  xtab <- crosstab(dframe, column, y_col)
  
  plot0 <- xtab %>%
    pivot_longer(cols = -!!sym(column),
                 names_to = "yvar",
                 values_to = "val") %>%
    ggplot() +
    aes(x = round(!!sym(column)),
        y = val,
        col = yvar %>% factor(),
        fill = yvar %>% factor()) +
    scale_fill_viridis_d() + scale_color_viridis_d() +
    theme_minimal() 
  
  p1 <- plot0 + geom_col(position = "stack")+
    labs(col = "Target Variable",
         fill = "Target Variable",
         y = "Count") +
    theme(legend.position = "none")
  p2 <- plot0 + geom_col(position = "fill")+
    labs(col = "Target Variable",
         fill = "Target Variable",
         y = "Proportion")
  p <- (p1 | p2)
  return(p)
}

var_na <- function(dframe, column, y_col) {
  xtab <- crosstab(dframe, column, y_col)
  newcolname <- paste(column, sep = "")
  
  out <- xtab %>%
    mutate(is_na = ifelse(is.na(!!sym(column)) == 1, 1, 0)) %>%
    group_by(is_na) %>%
    summarise(`0` = sum(`0`),
              `1` = sum(`1`)) %>%
    mutate(n = (`1` + `0`),
           survival_ratio = `1` / (`1` + `0`))
  
  colnames(out)[1] <- newcolname
  
  return(out)
}
```

```{r}
get_na_table <- function(dframe, column, y_col){
  dt <- var_na(dframe, column, y_col) %>% select(!!sym(column),n,survival_ratio)
  
  col <- c(col = column,
    dt[2,2]/(sum(dt[2])),
    dt[1,3],
    dt[2,3]) %>% 
  as.data.frame() %>% 
  rename(NAs = n,
         rate.rest = survival_ratio,
         rate.NAs  = survival_ratio.1)
  
  return(col)
}

all_na_table <- function(dframe,y_col){
  names <- colnames(dframe)
  
  table <- data.frame()
  
  for (i in names){
    if (i == y_col){
      break
    } else {
      table <- table %>% rbind(
        get_na_table(dframe,i,y_col)
      )
    }
  }
  
  return(table)
}

all_crosstabs <- function(dframe,y_col){
  names <- colnames(dframe)
  table <- data.frame()
  
  for (i in names){
    if (i == y_col){
      next
    } else {
      newtab <- crosstab(dframe,i,y_col) %>% 
        mutate(
          variable = i
        ) %>% 
        rename(
          value = !!sym(i)
        ) %>% 
        mutate(
          value = value %>% factor()
        ) %>% 
        select(variable,everything())
      
      table <- table %>% rbind(newtab)
    }
  }
  return(table)
}
```

```{r}
dat_d <- dat %>% 
  select(t_score,
         n_score,
         m_score,
         stage,
         race,
         family_history,
         first_degree_history,
         previous_cancer,
         smoker,
         side,
         tea,
         rd_thrpy,
         h_thrpy,
         chm_thrpy,
         cry_thrpy,
         brch_thrpy,
         rad_rem,
         multi_thrpy,
         survival_1_year,
         y)
```


```{r}
all_crosstabs(dat_d,"y") %>% 
  write_csv("data/discrete_tabs.csv")
```

