---
title: 'Mission Hospital Case: Workbook'
author: "Robert MD Bui"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("G:/My Drive/academics/2122_uic_ms/2022_spring/ids506_health/mission")

library(tidyverse) |> suppressPackageStartupMessages()
library(tidymodels) %>% suppressPackageStartupMessages()
library(patchwork) %>% suppressPackageStartupMessages()
library(kableExtra) %>% suppressPackageStartupMessages()
library(Cairo) %>% suppressPackageStartupMessages()
```

# Cleaning

```{r}
# Loading custom scripts
source("scripts/clean_data.R")
source("scripts/na_table.R")

df <- clean_data(read_csv("data/sheet4.csv",show_col_types = FALSE))
na_table(df)

# write_csv(df,"data/data.csv")
# write_csv(df_naomit,"data/data_naomit.csv")

```

# Exploratory Analysis

```{r}
####################################### DISCRETE PLOTTING FUNCTION #############################
plot_discrete <- function(dframe,ycol = "y",col){
  pbase <- dframe %>% 
    ggplot()+
    aes(x = !!sym(ycol),
        fill = !!sym(col))+
    scale_fill_viridis_d()+
    theme_minimal()
  
  (pbase + 
      geom_histogram(bins = 10,position="fill") + 
      theme(legend.position = "none")) | (pbase + geom_histogram(bins = 10))
}

####################################### CONTINUOUS PLOTTING FUNCTION ############################
plot_continuous <- function(dframe,ycol = "y",col){
  pbase <- dframe %>% 
    ggplot()+
    aes(y = !!sym(ycol),
        x = !!sym(col))+
    geom_point(color = "#440154")+
    geom_smooth(color = "#fde725", method = "lm")+
    scale_fill_viridis_d()+
    theme_minimal()
  return(pbase)
}
```



```{r}
####################################### DRAW ALL PLOTS ##########################################
index <- df %>% 
  select(-c(id,cost,cost_ln)) %>% 
  sapply(typeof) %>% 
  as.data.frame() %>% 
  rownames_to_column("colname")

colnames(index) <- c("colname","coltype")

for(i in (1:nrow(index))){
  name = index[i,1]
  type = index[i,2]
  
  if(type %in% c("double","numeric","integer")){
    plt.title <- paste("Figure ",i,": Plotting ",name, " against Target Variable",sep = "")
    print(plot_continuous(df,"cost",name)+ggtitle(plt.title))
  }else if(type %in% c("factor","logical")){
    plt.title <- paste("Figure ",i,": Plotting ",name, " against Target Variable",sep = "")
    print(plot_discrete(df,"cost",name)+plot_annotation(title = plt.title))
  }
}
```

# Splitting Train/Test Sets

```{r}
####################################### SPLITTING #######################################
d <- df %>% na.omit() 
na_table(d)

set.seed(8675309)
splitkey <- initial_split(d,
                          prop = .9,
                          strata = cost)
d.train <- training(splitkey)
d.test  <- testing(splitkey)
```

# Single Regression: Body Weight

```{r}
####################################### SINGLE-X REGRESSION #######################################
# Set preprocessing recipe
shortLM.rc <- recipe(cost ~ body_wgt,
                     data = d.train)

# Set engine
shortLM.en <- linear_reg() %>% set_engine("lm")

# Combining recipe + engine
shortLM.wf <- workflow() %>% 
  add_model(shortLM.en) %>% 
  add_recipe(shortLM.rc)

# Fitting
set.seed(8675309)
shortLM.ft <- shortLM.wf %>% fit(data=d.train)

# Fit Summary
shortLM.sm <- shortLM.ft %>% 
  extract_fit_parsnip() %>% 
  tidy()

shortLM.sm
```

```{r}
####################################### TEST SET ACCURACY: MAPE #######################################
shortLM.pred <- shortLM.ft %>% last_fit(splitkey) %>% collect_predictions()

mape(shortLM.pred,
     truth = cost,
     estimate = .pred)
```

# Multiple Regression: Kitchen Sink without Leaks

```{r}
####################################### MULTIPLE REGRESSION #######################################
# Set preprocessing recipe
multiLM.rc <- recipe(cost ~ .,
                     data = d.train) %>% 
  step_mutate(body_bmi  = body_wgt/((body_hgt/100)^2), role = "redundant") %>% 
  step_mutate(wgt_under = ifelse(body_bmi < 18.5,                 TRUE,FALSE),
              wgt_norml = ifelse(18.5 <= body_bmi & body_bmi < 25,TRUE,FALSE),
              wgt_overw = ifelse(25 <= body_bmi & body_bmi <= 30, TRUE,FALSE),
              wgt_obese = ifelse(30 < body_bmi,                   TRUE,FALSE)) %>% 
  update_role(c(cost_ln,stay_total,implant_cost,body_wgt,body_hgt),new_role = "redundant") %>% 
  update_role(c(
    # Setting leakages
    tidyselect::starts_with("code"),
    tidyselect::starts_with("stay"),
    tidyselect::starts_with("implant")
  ),new_role = "leakage") %>% 
  update_role(id,new_role = "ID") %>% 
  step_zv(all_numeric_predictors())
  
# Set engine
multiLM.en <- linear_reg() %>% set_engine("lm")

# Combining recipe + engine
multiLM.wf <- workflow() %>% 
  add_model(multiLM.en) %>% 
  add_recipe(multiLM.rc)

# Fitting
set.seed(8675309)
multiLM.ft <- multiLM.wf %>% fit(data=d.train)

# Fit Summary
multiLM.sm <- multiLM.ft %>% 
  extract_fit_parsnip() %>% 
  tidy()

multiLM.sm %>% 
  #filter(term != "(Intercept)") %>% 
  arrange(p.value)
```

```{r}
####################################### TEST SET ACCURACY: MAPE #######################################
multiLM.pred <- multiLM.ft %>% last_fit(splitkey) %>% collect_predictions()

mape(multiLM.pred,
     truth = cost,
     estimate = .pred)
```
